[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.3.0"
authors = ["Stephen Diehl <stephen.m.diehl@gmail.com>"]
categories = ["algorithms", "mathematics"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/sdiehl/zippel"
rust-version = "1.88"

[workspace.dependencies]
groebner = { version = "0.5.1", git = "https://github.com/sdiehl/groebner.git", rev = "a23ad57ec139f997a7e97ccdeefe290cf572abc7", default-features = false }
insta = { version = "1.41", features = ["glob"] }
num-bigint = "0.4"
num-integer = "0.1"
num-rational = "0.4"
num-traits = "0.2"
polycore = { version = "0.1.6", git = "https://github.com/sdiehl/polycore.git", rev = "421183e8158a718a0b16ad7e1f826c431925926a" }
polyfactor = { version = "0.1.6", git = "https://github.com/sdiehl/polycore.git", rev = "421183e8158a718a0b16ad7e1f826c431925926a" }
rayon = "1.10"
zippel-interp = { path = "crates/interp", version = "0.3.0", default-features = false }
zippel-lift = { path = "crates/lift", version = "0.3.0", default-features = false }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"
unreachable_pub = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

[patch.crates-io]
polycore = { version = "0.1.6", git = "https://github.com/sdiehl/polycore.git", rev = "421183e8158a718a0b16ad7e1f826c431925926a" }
groebner = { version = "0.5.1", git = "https://github.com/sdiehl/groebner.git", rev = "a23ad57ec139f997a7e97ccdeefe290cf572abc7" }
