[package]
name = "zippel-gcd"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords = ["polynomial", "gcd", "zippel", "algebra"]
license.workspace = true
readme.workspace = true
repository.workspace = true
description = "Sparse multivariate polynomial GCD by Zippel's modular interpolation."

[features]
default = ["parallel"]
parallel = ["zippel-interp/parallel"]

[dependencies]
groebner.workspace = true
num-bigint.workspace = true
num-integer.workspace = true
num-rational.workspace = true
num-traits.workspace = true
zippel-interp.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
