[package]
name = "zippel-interp"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords = ["polynomial", "interpolation", "zippel", "finite-field"]
license.workspace = true
readme.workspace = true
repository.workspace = true
description = "Black-box sparse polynomial and rational function interpolation over word-sized prime fields."

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
rayon = { workspace = true, optional = true }

[lints]
workspace = true
