[package]
name = "zippel-interp"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords = ["polynomial", "interpolation", "zippel", "finite-field"]
license.workspace = true
readme.workspace = true
repository.workspace = true
description = "Black-box sparse polynomial interpolation over word-sized prime fields."

[lints]
workspace = true
