[package]
name = "zippel-interp"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords = ["polynomial", "interpolation", "zippel", "finite-field"]
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Black-box sparse polynomial and rational function interpolation over word-sized prime fields."

[features]
default = ["parallel"]
parallel = ["polycore/parallel"]

[dependencies]
polycore.workspace = true
polyfactor = { path = "../../../poly-core/crates/polyfactor", version = "0.1.5" }

[lints]
workspace = true
